<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SewerScan.Application\SewerScan.Application.csproj" />
    <ProjectReference Include="..\..\src\SewerScan.Domain\SewerScan.Domain.csproj" />
  </ItemGroup>

</Project>
